import "./navbar.js";
import "../validation/handle-switching-forms.js";
import { formSignUpFunc } from "../validation/form-signUp.js";
import { formSignIn } from "../validation/form-signIn.js";
import "../validation/close-form.js";
import { generateData } from "./handle-menu-list.js";
import { generateDishesData } from "./handle-dishes-list.js";
import { createIcons, icons } from "lucide";
import { goToTop, scrollHeader } from "./scroll-header.js";
import { cartCount } from "./cart-count.js";
import { generateDataDashes, searchProduct } from "./search-product.js";

formSignUpFunc();
formSignIn();
generateData();
generateDishesData();
scrollHeader();
createIcons({ icons });
cartCount();
searchProduct();
generateDataDashes();
goToTop();
